---
# tasks file for webserver
- name: "Install NGINX"
  become: yes
  apt:
    name: nginx
    update_cache: yes
  
- name: "Remove index.nginx-debian.html"
  become: yes
  file: 
    path: /var/www/html/index.nginx-debian.html
    state: absent
  
- name: "Copy website files"  
  become: yes 
  copy:
    src: html/
    dest: /var/www/html
  